# Generated by Django 4.1.5 on 2023-01-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(default="2022/23", max_length=16)),
                ("start_date", models.DateField()),
                ("report_deadline", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12)),
                ("description", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("tag", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given_name", models.CharField(max_length=200)),
                ("family_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "srs",
                    models.CharField(
                        max_length=11, verbose_name="Student Record System ID"
                    ),
                ),
                (
                    "parttime",
                    models.BooleanField(default=False, verbose_name="Part-time"),
                ),
                (
                    "distance",
                    models.BooleanField(default=False, verbose_name="Distance learner"),
                ),
                ("research_question", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dissertations.academicyear",
                    ),
                ),
                ("methods", models.ManyToManyField(to="dissertations.researchmethod")),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dissertations.programme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given_name", models.CharField(max_length=200)),
                ("family_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("methods", models.ManyToManyField(to="dissertations.researchmethod")),
                ("topics", models.ManyToManyField(to="dissertations.researchtopic")),
            ],
        ),
        migrations.CreateModel(
            name="StudentSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dissertations.student",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dissertations.supervisor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="supervisors",
            field=models.ManyToManyField(
                through="dissertations.StudentSupervisor", to="dissertations.supervisor"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="topics",
            field=models.ManyToManyField(to="dissertations.researchtopic"),
        ),
    ]
