# Generated by Django 4.1.5 on 2023-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="methods",
            field=models.ManyToManyField(blank=True, to="dissertations.researchmethod"),
        ),
        migrations.AlterField(
            model_name="student",
            name="topics",
            field=models.ManyToManyField(blank=True, to="dissertations.researchtopic"),
        ),
    ]
