# Generated by Django 4.1.5 on 2023-01-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0002_alter_student_methods_alter_student_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsupervisor",
            name="confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
