# Generated by Django 4.1.5 on 2023-01-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0003_alter_studentsupervisor_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisor",
            name="methods",
            field=models.ManyToManyField(blank=True, to="dissertations.researchmethod"),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="topics",
            field=models.ManyToManyField(blank=True, to="dissertations.researchtopic"),
        ),
    ]
